"""Small SQL backend abstraction for SQLite and PostgreSQL."""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator
from urllib.parse import unquote

try:  # pragma: no cover - optional dependency for PostgreSQL mode
    import psycopg
except ImportError:  # pragma: no cover - sqlite-only local runs are valid
    psycopg = None


class SQLConnection:
    """Thin wrapper that normalizes placeholder styles across drivers."""

    def __init__(self, raw_connection, backend: "SQLBackend") -> None:
        self._raw = raw_connection
        self._backend = backend

    def execute(self, sql: str, params: tuple | list = ()):
        return self._raw.execute(self._backend.sql(sql), params)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


class SQLBackend:
    """Environment-driven SQL backend with SQLite default and PostgreSQL support."""

    def __init__(self, engine: str, sqlite_path: Path | None = None, database_url: str = "") -> None:
        self.engine = engine
        self.sqlite_path = sqlite_path
        self.database_url = database_url

    @classmethod
    def from_env(cls, sqlite_path: Path, env_var: str = "SHIPSENSE_DATABASE_URL") -> "SQLBackend":
        database_url = os.getenv(env_var, "").strip()
        if database_url.startswith(("postgres://", "postgresql://")):
            return cls("postgres", database_url=database_url)
        if database_url.startswith("sqlite:///"):
            resolved = Path(unquote(database_url.removeprefix("sqlite:///"))).expanduser()
            return cls("sqlite", sqlite_path=resolved)
        return cls("sqlite", sqlite_path=sqlite_path)

    @property
    def name(self) -> str:
        return self.engine

    @property
    def integrity_errors(self) -> tuple[type[BaseException], ...]:
        errors: list[type[BaseException]] = [sqlite3.IntegrityError]
        if psycopg is not None:
            errors.append(psycopg.IntegrityError)
        return tuple(errors)

    def sql(self, statement: str) -> str:
        if self.engine == "postgres":
            return statement.replace("?", "%s")
        return statement

    def identity_primary_key(self) -> str:
        if self.engine == "postgres":
            return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        return "INTEGER PRIMARY KEY AUTOINCREMENT"

    @contextmanager
    def connect(self, autocommit: bool = False) -> Iterator[SQLConnection]:
        raw = self._open_raw_connection(autocommit=autocommit)
        connection = SQLConnection(raw, self)
        try:
            yield connection
            if not autocommit:
                raw.commit()
        except Exception:
            if not autocommit:
                raw.rollback()
            raise
        finally:
            raw.close()

    def column_names(self, conn: SQLConnection, table: str) -> set[str]:
        if self.engine == "postgres":
            rows = conn.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = ?
                """,
                (table,),
            ).fetchall()
            return {row[0] for row in rows}
        rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
        return {row[1] for row in rows}

    def _open_raw_connection(self, autocommit: bool):
        if self.engine == "postgres":
            if psycopg is None:
                raise RuntimeError(
                    "PostgreSQL support requires the optional 'psycopg[binary]' package."
                )
            return psycopg.connect(self.database_url, autocommit=autocommit)
        if not self.sqlite_path:
            raise RuntimeError("SQLite backend requires a filesystem path.")
        self.sqlite_path.parent.mkdir(parents=True, exist_ok=True)
        isolation_level = None if autocommit else "DEFERRED"
        return sqlite3.connect(self.sqlite_path, isolation_level=isolation_level)
