[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /logs/app.log
    Tag               shipsense.app
    Read_from_Head    true
    Parser            shipsense_log
    DB                /tmp/shipsense-fluentbit.db

[FILTER]
    Name              record_modifier
    Match             shipsense.app
    Record            service shipsense-api
    Record            environment local-demo

[OUTPUT]
    Name              es
    Match             shipsense.app
    Host              elasticsearch
    Port              9200
    Index             shipsense-logs
    Logstash_Format   On
    Replace_Dots      On
    Suppress_Type_Name On
